tasks:
# 
  - before: wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
            sudo dpkg -i packages-microsoft-prod.deb && \
            rm packages-microsoft-prod.deb && \
  - init:   sudo apt update && \
            sudo apt install -y apt-transport-https && \
            sudo apt upgrade && \
            sudp apt update && \ 
            sudo apt-get install -y dotnet-sdk-6.0 aspnetcore-runtime-6.0 

vscode:
  extensions:
    - jsw.csharpextensions